name = "argus"
version = "1.0.1"
description = "Argon2 password hashing library for Gleam, based on the reference C implementation."
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "argus" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
jargon = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.4.0 and < 1.0.0"
